core/src/main/scala/org/http4s/blaze/util/TickWheelExecutor.scala

closes #8
This change doesn't have a major impact on performance but significantly reduces complexity (though not LOC).
I imagine I'm the only one that will be concerned with this, but I thought I'd throw it up as a PR anyway just in case someone wanted to give it a quick review.

Implement the lock free tickwheel executor.

---

core/src/main/scala/org/http4s/blaze/channel/ChannelHead.scala
core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1HeadStage.scala
core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1ServerChannelFactory.scala
core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1SocketServerChannelFactory.scala
core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoop.scala
core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoopPool.scala
core/src/main/scala/org/http4s/blaze/channel/nio2/ByteBufferHead.scala
core/src/main/scala/org/http4s/blaze/pipeline/Command.scala
core/src/main/scala/org/http4s/blaze/pipeline/Stages.scala
core/src/main/scala/org/http4s/blaze/pipeline/stages/CommandTimeoutStage.scala
core/src/main/scala/org/http4s/blaze/pipeline/stages/HubStage.scala
core/src/main/scala/org/http4s/blaze/pipeline/stages/SSLStage.scala
core/src/main/scala/org/http4s/blaze/pipeline/stages/SerializingStage.scala
core/src/main/scala/org/http4s/blaze/pipeline/stages/TimeoutStageBase.scala
core/src/main/scala/org/http4s/blaze/pipeline/stages/addons/Serializer.scala
core/src/main/scala/org/http4s/blaze/util/Actors.scala
core/src/main/scala/org/http4s/blaze/util/BufferTools.scala
core/src/test/scala/org/http4s/blaze/pipeline/PipelineSpec.scala
core/src/test/scala/org/http4s/blaze/pipeline/stages/HubStageSpec.scala
core/src/test/scala/org/http4s/blaze/pipeline/stages/SSLStageSpec.scala
core/src/test/scala/org/http4s/blaze/util/BufferToolsSpec.scala

Also some general cleanup of things that were ill designed/ugly code.
I'd appreciate any bit of code review anybody can give me here. Thanks for the help.

Changes to blaze-core to support http20

---

examples/src/main/scala/org/http4s/blaze/examples/http20/Http2Server.scala
http/src/main/scala/org/http4s/blaze/http/http20/ALPNSelector.scala
http/src/main/scala/org/http4s/blaze/http/http20/Http2Selector.scala
project/build.scala

* Add recognition of 'h2' protocol string
* Code cleanup

Refine the ALPN selector

---

core/src/main/scala/org/http4s/blaze/channel/nio2/ClientChannelFactory.scala

Nonfatal exceptions are caught and used to complete the Future with a
failure.

Handle the error associated with opening a connection

---

core/src/main/scala/org/http4s/blaze/pipeline/Stages.scala
core/src/test/scala/org/http4s/blaze/pipeline/PipelineSpec.scala

Added tests and fixed the broken spliceBefore on Head stage.

Add ability to splice stages before a Tail stage

---

core/src/main/scala/org/http4s/blaze/channel/nio2/ByteBufferHead.scala

This will help avoid leaking resources when using the blaze nio2 pipeline tools.

Add a finalizer to ByteBufferHead

---

core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1HeadStage.scala
core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1SocketServerGroup.scala
core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoop.scala
core/src/main/scala/org/http4s/blaze/pipeline/stages/SerializingStage.scala

@bryce-anderson just say if you want me to rework the pull request before you merge it.

Code review changes, mostly just comments

---

http/src/main/java/org/http4s/blaze/http/http_parser/BodyAndHeaderParser.java
http/src/main/java/org/http4s/blaze/http/http_parser/Http1ClientParser.java
http/src/main/java/org/http4s/blaze/http/http_parser/Http1ServerParser.java
http/src/main/scala/org/http4s/blaze/http/HttpClientStage.scala
http/src/test/scala/org/http4s/blaze/http/http_parser/ClientParserSpec.scala
http/src/test/scala/org/http4s/blaze/http/http_parser/ServerParserSpec.scala

Code-review changes with intent to make the code one step closer to what the specification mandates.

Content-Length and Transfer-Encoding handling

---

http/src/main/java/org/http4s/blaze/http/parser/BaseExceptions.java
http/src/main/java/org/http4s/blaze/http/parser/BodyAndHeaderParser.java
http/src/main/java/org/http4s/blaze/http/parser/Http1ClientParser.java
http/src/main/java/org/http4s/blaze/http/parser/Http1ServerParser.java
http/src/main/java/org/http4s/blaze/http/parser/HttpTokens.java
http/src/main/java/org/http4s/blaze/http/parser/ParserBase.java
http/src/main/scala/org/http4s/blaze/http/HttpServerStage.scala
http/src/main/scala/org/http4s/blaze/http/client/HttpClientStage.scala
http/src/test/scala/org/http4s/blaze/http/HttpServerStageSpec.scala
http/src/test/scala/org/http4s/blaze/http/parser/BenchParser.scala
http/src/test/scala/org/http4s/blaze/http/parser/Benchmarks.scala
http/src/test/scala/org/http4s/blaze/http/parser/ClientParserSpec.scala
http/src/test/scala/org/http4s/blaze/http/parser/HttpTokensSpec.scala
http/src/test/scala/org/http4s/blaze/http/parser/ParserBaseSpec.scala
http/src/test/scala/org/http4s/blaze/http/parser/ResponseParser.scala
http/src/test/scala/org/http4s/blaze/http/parser/ServerParserSpec.scala

Rename package http_parser to parser

---

core/src/main/scala/org/http4s/blaze/pipeline/stages/SSLStage.scala

Fixes issue #71
To prevent SOEs, we make to looping parts of `SSLStage.sslHandshake`
tail recursive and wrap that in the try/catch block.
If this solves the issue, it should also be merged into master.

Trampoline SSLStage handshake

---

.travis.yml
build.sbt
project/build.properties
project/plugins.sbt

Went to do a simple update of a few of the dependencies, ended up needing to do a bit of a refactor on the build in order to get it all working as the deprecation window had expired. 
Everything seems to compile nicely now on my machine. However when build.sbt get changed I'd love as many eyes as possible.

Version updates

---

core/src/main/scala/org/http4s/blaze/channel/ServerChannelGroup.scala

Changed 'to' to 'from' for clarity

---

http/src/main/java/org/http4s/blaze/http/parser/Http1ClientParser.java
http/src/main/scala/org/http4s/blaze/http/ClientResponse.scala
http/src/main/scala/org/http4s/blaze/http/HttpClient.scala
http/src/main/scala/org/http4s/blaze/http/HttpClientConfig.scala
http/src/main/scala/org/http4s/blaze/http/HttpClientSession.scala

No implementations but the interfaces which will define the HTTP client.

Add new HTTP Client Interfaces

---

http/src/main/scala/org/http4s/blaze/http/http2/Http2Exception.scala
http/src/main/scala/org/http4s/blaze/http/http2/Http2Result.scala
http/src/main/scala/org/http4s/blaze/http/http2/Http2Settings.scala
http/src/main/scala/org/http4s/blaze/http/http2/bits.scala

Add some basic types necessary for HTTP/2

---

core/src/test/scala/org/http4s/blaze/util/TickWheelExecutorSpec.scala

CI jobs often have a problem with a timer thread
not getting scheduled within a timeout. This makes
the offending test depend on a CountdownLatch so
we don't have to sleep the thread for longer than
necessary.

Fix flaky test

---

core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoop.scala

Old method kept for binary compatibility, though I suspect it could be privatized.

Fix spelling of enqueueTask

---

core/src/main/scala/org/http4s/blaze/channel/package.scala

http4s-blaze-server delegates to this.

Backport change to default pool size

---

.travis.yml
build.sbt
project/BlazePlugin.scala

References Removal from Http4s in http4s/http4s#1337

Remove Typelevel Scala

---

core/src/test/scala/org/http4s/blaze/util/ActorSpec.scala

ActorSpec should throw the exception that causes it to halt

---

README.md

Got an urge to put the travis badge on the readme, so I put the maven badge as well... because?

Add Travis and Maven Badge to README

---

core/src/test/scala/org/http4s/blaze/pipeline/stages/SerializingStageSpec.scala
core/src/test/scala/org/http4s/blaze/pipeline/stages/SlowHead.scala

The tests previously made hundreds of threads which
is really poor form.

Make SerializingStageSpec deterministic

---

build.sbt

I see some issues with suppressing. However I worry how long we have been out of commission.
Other options are looking through what is necessary for upgrading rig.

Add Suppression Option to Scaladoc Linking

---

http/src/test/scala/org/http4s/blaze/http/http2/Http2StageToolsSpec.scala

Some basic tests for the rules of
Http2StageTools.validateHeaderName

Add Http2StageToolsSpec

---

http/src/main/scala/org/http4s/blaze/http/http2/StreamIdManager.scala
http/src/test/scala/org/http4s/blaze/http/http2/StreamIdManagerSpec.scala

Introduce the accounting abstraction for stream ids.

Add StreamIdManager

---

http/src/main/scala/org/http4s/blaze/http/http2/Http2Connection.scala
http/src/main/scala/org/http4s/blaze/http/http2/InboundStreamState.scala
http/src/main/scala/org/http4s/blaze/http/http2/OutboundStreamState.scala
http/src/main/scala/org/http4s/blaze/http/http2/StreamManager.scala
http/src/main/scala/org/http4s/blaze/http/http2/StreamState.scala
http/src/test/scala/org/http4s/blaze/http/http2/MockFlowControl.scala
http/src/test/scala/org/http4s/blaze/http/http2/OutboundStreamStateSpec.scala
http/src/test/scala/org/http4s/blaze/http/http2/StreamStateSpec.scala
http/src/test/scala/org/http4s/blaze/http/http2/mocks/MockStreamManager.scala
http/src/test/scala/org/http4s/blaze/http/http2/mocks/MockTools.scala

StreamState is the junction between the H2 session
and the individual dispatches.

Add StreamState

---

http/src/main/scala/org/http4s/blaze/http/http2/Http2Settings.scala
http/src/main/scala/org/http4s/blaze/http/http2/SessionFrameListener.scala
http/src/test/scala/org/http4s/blaze/http/http2/SessionFrameListenerSpec.scala

Implementation of a FrameListener that operates on the state of an
underlying SessionCore.

Add the SessionFrameListener

---

http/src/main/scala/org/http4s/blaze/http/http2/ConnectionImpl.scala
http/src/main/scala/org/http4s/blaze/http/http2/FrameSerializer.scala
http/src/main/scala/org/http4s/blaze/http/http2/SessionCore.scala
http/src/main/scala/org/http4s/blaze/http/http2/StreamManager.scala
http/src/main/scala/org/http4s/blaze/http/http2/StreamManagerImpl.scala
http/src/main/scala/org/http4s/blaze/http/http2/StreamMessage.scala
http/src/main/scala/org/http4s/blaze/http/http2/StreamStateImpl.scala
http/src/test/scala/org/http4s/blaze/http/http2/ConnectionImplSpec.scala
http/src/test/scala/org/http4s/blaze/http/http2/FrameSerializerSpec.scala
http/src/test/scala/org/http4s/blaze/http/http2/PingManagerSpec.scala
http/src/test/scala/org/http4s/blaze/http/http2/ProtocolFrame.scala
http/src/test/scala/org/http4s/blaze/http/http2/ProtocolFrameDecoder.scala
http/src/test/scala/org/http4s/blaze/http/http2/SessionFrameListenerSpec.scala
http/src/test/scala/org/http4s/blaze/http/http2/StreamManagerImplSpec.scala
http/src/test/scala/org/http4s/blaze/http/http2/mocks/MockHeadStage.scala
http/src/test/scala/org/http4s/blaze/http/http2/mocks/MockStreamManager.scala
http/src/test/scala/org/http4s/blaze/http/http2/mocks/MockTools.scala

This is a concrete implementation of a HTTP connection state machine.

Introduce ConnectionImpl

---

core/src/main/scala/org/http4s/blaze/util/BufferTools.scala
http/src/main/scala/org/http4s/blaze/http/http2/FlowStrategy.scala
http/src/main/scala/org/http4s/blaze/http/http2/PriorKnowledgeHandshaker.scala
http/src/main/scala/org/http4s/blaze/http/http2/bits.scala
http/src/main/scala/org/http4s/blaze/http/http2/client/ClientPriorKnowledgeHandshaker.scala
http/src/main/scala/org/http4s/blaze/http/http2/client/ClientSessionImpl.scala
http/src/main/scala/org/http4s/blaze/http/http2/server/ServerPriorKnowledgeHandshaker.scala
http/src/test/scala/org/http4s/blaze/http/http2/ClientPriorKnowledgeHandshakerSpecSpec.scala
http/src/test/scala/org/http4s/blaze/http/http2/PingManagerSpec.scala
http/src/test/scala/org/http4s/blaze/http/http2/ProtocolFrame.scala
http/src/test/scala/org/http4s/blaze/http/http2/ProtocolFrameDecoder.scala
http/src/test/scala/org/http4s/blaze/http/http2/ServerPriorKnowledgeHandshakerSpec.scala
http/src/test/scala/org/http4s/blaze/http/http2/mocks/MockHeadStage.scala

They are in change of handling the connection preface and sending and
receiving the initial settings frames.

Add PriorKnowledgeHandshaker for client and server

---

.travis.yml
build.sbt
http/src/main/scala/org/http4s/blaze/http/http2/server/AbstractBodyReader.scala
http/src/test/scala/org/http4s/blaze/http/http2/server/AbstractBodyReaderSpec.scala

It's role is to provide the application space a handle on the data from
the HTTP/2 stream.

Add the server AbstractBodyReader

---

examples/src/main/scala/org/http4s/blaze/examples/http2/Http2ServerExample.scala
http/src/main/scala/org/http4s/blaze/http/http2/server/ALPNServerSelector.scala
http/src/main/scala/org/http4s/blaze/http/http2/server/ServerSelector.scala

The final piece needed for making HTTP/2 server sessions

Add the HTTP/2 ServerSelector

---

build.sbt

Bump to version 0.14.0-SNAPSHOT

---

http/src/main/java/org/http4s/blaze/http/parser/Http1ServerParser.java

The naming is silly, so this brings it closer to something recognizable.

Cleanup the Http1ServerParser

---

http/src/main/scala/org/http4s/blaze/http/http1/server/Http1ServerCodec.scala

The Http1ServerCodec was satisfying a Promise while holding a lock which
is generally poor form since it can result in arbitrary execution and
potentially deadlocks.

Fix locking issue in Http1ServerCodec

---

build.sbt

Aligning with http4s's log4s version

Updgrade log4s to 1.6.1

---

.travis.yml

Build against oraclejdk10

---

project/BlazePlugin.scala

Cleans up a couple eviction warnings.

Bump dependencies

---

http/src/test/scala/org/http4s/blaze/http/endtoend/InfiniteSpec.scala

#215 was good. 
#216 was good.
#215 with #216 was no good.

Fix compilation error due to AHC upgrade

---

project/BlazePlugin.scala

Upgade alpn-runtime

---

build.sbt

This will unblock http4s/http4s#2146.

Release v0.14.0-M5

---

core/src/main/scala/org/http4s/blaze/pipeline/stages/SSLStage.scala

Fixes issue http4s/http4s#2259, I think.

A handshake can have a status of NOT_HANDSHAKING after all

---

core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoop.scala
core/src/main/scala/org/http4s/blaze/channel/nio2/ByteBufferHead.scala
core/src/main/scala/org/http4s/blaze/pipeline/Stages.scala
core/src/main/scala/org/http4s/blaze/pipeline/stages/SSLStage.scala
core/src/main/scala/org/http4s/blaze/util/Execution.scala
core/src/test/scala/org/http4s/blaze/pipeline/stages/SSLStageSpec.scala
core/src/test/scala/org/http4s/blaze/util/ExecutionSpec.scala
http/src/main/scala/org/http4s/blaze/http/ClientResponse.scala
http/src/main/scala/org/http4s/blaze/http/http1/server/Http1ServerCodec.scala
http/src/main/scala/org/http4s/blaze/http/http2/client/ALPNClientSelector.scala
http/src/main/scala/org/http4s/blaze/http/http2/server/ALPNServerSelector.scala

Don't catch fatal exceptions

---

core/src/main/scala/org/http4s/blaze/util/TickWheelExecutor.scala

Align TickWheelExecutor.cycle executions to time divisible by tick.

---

core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoop.scala

This cause the following spurious exceptions to be thrown on normal http4s termination (if there were keep-alive connections open):
```
16:04:38.781 [blaze-selector-1] ERROR o.h.blaze.channel.nio1.NIO1HeadStage - Abnormal NIO1HeadStage termination
java.nio.channels.ShutdownChannelGroupException: null
at org.http4s.blaze.channel.nio1.SelectorLoop.killSelector(SelectorLoop.scala:226)
at org.http4s.blaze.channel.nio1.SelectorLoop.org$http4s$blaze$channel$nio1$SelectorLoop$$runLoop(SelectorLoop.scala:186)
at org.http4s.blaze.channel.nio1.SelectorLoop$$anon$1.run(SelectorLoop.scala:68)
at java.lang.Thread.run(Thread.java:748)
16:04:38.781 [blaze-selector-1] ERROR o.h.s.blaze.Http1ServerStage$$anon$1 - Fatal Error: Error in requestLoop()
java.nio.channels.ShutdownChannelGroupException: null
at …
```

Fix spurious exception on normal termination of a `SelectorLoop`.

---

.travis.yml
build.sbt

scala 2.13.2

---

build.sbt
http/src/main/java/org/http4s/blaze/http/parser/Http1ClientParser.java
http/src/main/java/org/http4s/blaze/http/parser/ParserBase.java

javafmt enforcement

---

.github/workflows/ci.yml
build.sbt
project/Dependencies.scala

Helping with https://github.com/http4s/http4s/pull/4681

Out with 3.0.0-M3, in with Scala 3.0.0-RC2

---

.github/workflows/ci.yml
build.sbt

PublishTags

---

.github/workflows/ci.yml
project/plugins.sbt

That plugin is no longer needed because of the SBT version. See https://www.scala-lang.org/blog/2021/04/08/scala-3-in-sbt.html

Rm sbt-dotty plugin

---

.github/workflows/ci.yml
build.sbt

It might be helpful in the local development process.

Add cross-compiling check to the validate command

---

README.md

This is a minor thing, but some cleanup.

Fix CI badge in `README.md`

---

project/plugins.sbt

Rm `sbt-updates` plugin

---

.mergify.yml

Nothing to see here, just my poor attempts to set up labeling powered by Mergify.

Merge `series/0.23` into `main`

---

.scala-steward.conf

We will get them from the 0.23 branch.

Ignore `circe-generic` updates

---

.scala-steward.conf

We will get updates from the 0.23 branch.

Ignore Scala updates

---

blaze-core/src/main/scala/org/http4s/blazecore/util/IdentityWriter.scala

Cherry-pick of #789 to series/0.23 for faster production release.

Minimize logger creation impact in IdentityWriter (0.23)

---

blaze-server/src/test/scala/org/http4s/blaze/server/BlazeServerSuite.scala

Closes https://github.com/http4s/blaze/issues/819

Mark "reliably handle multipart requests" test flaky
