- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1ServerChannelFactory.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1SocketServerChannelFactory.scala
- core/src/main/scala/org/http4s/blaze/channel/nio2/NIO2SocketServerChannelFactory.scala
- core/src/main/scala/org/http4s/blaze/channel/package.scala
- core/src/test/scala/org/http4s/blaze/channel/ChannelSpec.scala
- examples/src/main/scala/org/http4s/blaze/examples/ClientAuthSSLHttpServer.scala
- examples/src/main/scala/org/http4s/blaze/examples/EchoServer.scala
- examples/src/main/scala/org/http4s/blaze/examples/NIO1HttpServer.scala
- examples/src/main/scala/org/http4s/blaze/examples/NIO2HttpServer.scala
- examples/src/main/scala/org/http4s/blaze/examples/SSLHttpServer.scala
- examples/src/main/scala/org/http4s/blaze/examples/WebSocketServer.scala
- examples/src/main/scala/org/http4s/blaze/examples/http20/Http2Server.scala
- examples/src/main/scala/org/http4s/blaze/examples/spdy/SpdyServer.scala
Use companion object methods instead of `new` operators.
This is really a simple cleanup to make things more idiomatic scala and less java written in scala.
> Clean up how a ChannelFactory is constructed

- core/src/main/scala/org/http4s/blaze/channel/ServerChannel.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1ServerChannelFactory.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoop.scala
- core/src/main/scala/org/http4s/blaze/channel/nio2/NIO2SocketServerChannelFactory.scala
- core/src/test/scala/org/http4s/blaze/channel/ChannelSpec.scala
This fixes https://github.com/http4s/http4s/issues/231.
NIO1 was neglecting shutdown hooks, among other things.
NIO2 was needlessly throwing errors.
> Clean up shutdown mechanisms.

- http/src/main/java/org/http4s/blaze/http/http_parser/ParserBase.java
- http/src/test/scala/org/http4s/blaze/http/http_parser/ServerParserSpec.scala
Associated with https://github.com/http4s/http4s/issues/236
This should be a no brainer: the old spec (http://tools.ietf.org/html/rfc2616#section-19.3) recommends allowing LF without the preceeding CR. Note I didn't see this in rfc 7230 which replaces 2616, but I believe it should still apply.
I'll merge this shortly unless there is objection.
> Accept a bare LF in the status line and headers

- core/src/main/scala/org/http4s/blaze/pipeline/stages/TimeoutStageBase.scala
- core/src/main/scala/org/http4s/blaze/util/Cancellable.scala
- core/src/main/scala/org/http4s/blaze/util/TickWheelExecutor.scala
- core/src/test/scala/org/http4s/blaze/pipeline/stages/QuietTimeoutStageSpec.scala
- core/src/test/scala/org/http4s/blaze/pipeline/stages/TimeoutHelpers.scala
- examples/src/main/scala/org/http4s/blaze/examples/HttpServer.scala
There was a condition where the tail performs a read/write request, and before it is honored, the pipeline gets shutdown (maybe by a disconnect). That disconnect shuts down the pipeline and cancels any pending timeouts. However, the pending IO request _should_ eventually resolve, and that will reset the stage again, scheduling another timeout.
This PR addresses this by flagging the atomic reference with a 'tag' which it checks when resetting the timeout and acts appropriately.
> Fix QuietTimeoutStage so that it will cancel unused resets after its shutdown

- http/src/main/java/org/http4s/blaze/http/http_parser/Http1ClientParser.java
- http/src/test/scala/org/http4s/blaze/http/http_parser/ClientParserSpec.scala
> Bugfix when parsing http response status-line without reason-phrase

- core/src/main/scala/org/http4s/blaze/channel/ServerChannel.scala
- core/src/main/scala/org/http4s/blaze/channel/ServerChannelGroup.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1SocketServerGroup.scala
- core/src/main/scala/org/http4s/blaze/channel/nio2/NIO2SocketServerGroup.scala
This is so we can expose the bound port on the `BlazeServer`, for when it's constructed to listen on port 0.
> Add InetSocketAddress to server chsocket address to server channel.

- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1SocketServerGroup.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoop.scala
- core/src/main/scala/org/http4s/blaze/channel/nio2/ByteBufferHead.scala
- core/src/main/scala/org/http4s/blaze/util/BufferTools.scala
- core/src/main/scala/org/http4s/blaze/util/ScratchBuffer.scala
- core/src/test/scala/org/http4s/blaze/channel/EchoStage.scala
- core/src/test/scala/org/http4s/blaze/pipeline/stages/ByteToObjectStageSpec.scala
- core/src/test/scala/org/http4s/blaze/pipeline/stages/SSLStageSpec.scala
- core/src/test/scala/org/http4s/blaze/util/BufferToolsSpec.scala
Problem
The java NIO implementation leaks direct memory because of the
way that it caches temporary direct ByteBuffers. This can lead
to OOM like errors.
Solution
Ensure that the scratch buffer is a direct ByteBuffer, and copy
heap buffers into it before writing, essentially stepping around
the logic that the JDK uses to write heap buffers.
Details
- Add additional allocation methods to BufferTools to be more
explicit.
- Use direct ByteBuffers for the scratch buffers in in NIO1 and NIO2
because they will most often be talking directly to the socket and
would necessitate a copy.
- Make tools for copying and fast forwarding ByteBuffers
- Fix the memory leak.
- Add a write loop so we saturate the tcp buffer without doing
excessive copies that are then discarded.
- Be awesome.
> Work around the java Socket "memory leak"

- build.sbt
We used to support Java 1.7 on Scala 2.10, but never applied it to Java.
De facto, we already released for Java 1.8.  Making it explicit so this
doesn't kill us in 1.9.
> Explicitly set targets in Java and Scala

- core/src/main/scala/org/http4s/blaze/pipeline/Stages.scala
- http/src/main/scala/org/http4s/blaze/http/HttpServerStage.scala
- http/src/main/scala/org/http4s/blaze/http/http20/ALPNSelector.scala
* The `replaceNext` method can be on `Head`, not just `MidStage`
* Remove a default argument from `replaceNext` since its good
to think about the meaning of that argument.
* Added some minimal doc strings to the important methods
> Clean up a few warts of the Stages api

- build.sbt
- core/src/main/scala/org/http4s/blaze/channel/ChannelOptions.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1SocketServerGroup.scala
- core/src/main/scala/org/http4s/blaze/channel/nio2/ClientChannelFactory.scala
- core/src/main/scala/org/http4s/blaze/channel/nio2/NIO2SocketServerGroup.scala
- core/src/main/scala/org/http4s/blaze/channel/nio2/package.scala
- core/src/test/scala/org/http4s/blaze/channel/ChannelOptionsSpec.scala
Fixes #46
Add `ChannelOptions`, a collection of ChannelOption->value pairs
that can be applied to a socket connection. These are passed to
the common vectors of socket generation to configure the socket
after its connected.
Also perform some minor API cleanup: make classes final, etc.
> Add ability to configure channel options

- core/src/main/scala/org/http4s/blaze/util/BufferTools.scala
- core/src/test/scala/org/http4s/blaze/util/BufferToolsSpec.scala
It makes it difficult to reason about the state
of the buffer you're holding because slices can
find themselves corrupted after the concat.
> Don't compact in BufferTools.concatBuffers

- LICENSE
This is the proper thing to do when adding the LICENSE file to the
root directory of a OSS project.
> Add full text of the Apache-2 license

- README.md
The README.md suggests that blaze is unstable and full of bugs when
the reality is that it is reasonably mature and it is the API that
remains in flux as it may need to evolve to support the core http4s
project. This commit updates the README.md to better reflect that
reality.
> Make README.md not scary

- core/src/main/scala/org/http4s/blaze/pipeline/stages/SSLStage.scala
- core/src/main/scala/org/http4s/blaze/util/package.scala
Fixes #75
If the handshake fails the SSLEngine.unwrap(..) call will result in a
status of CLOSED but we don't check that case and just continue the
loop. Forever.
Thanks @tanaka-de-silva for reporting and @svalaskevicius helping diagnose!
> Fix infinite loop on ssl handshake failure

- core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoop.scala
- http/src/main/java/org/http4s/blaze/http/parser/BodyAndHeaderParser.java
- http/src/main/scala/org/http4s/blaze/http/ALPNTokens.scala
- http/src/main/scala/org/http4s/blaze/http/BodyReader.scala
- http/src/test/scala/org/http4s/blaze/http/BodyReaderSpec.scala
BodyReader is going to be the core abstraction for extracting data from
a HTTP message body and ALPNTokens are going to be necessary for
performing ALPN negotiation between HTTP/1.x and HTTP/2.
> Add BodyReader and ALPNTokens

- core/src/main/scala/org/http4s/blaze/channel/ServerChannel.scala
- core/src/test/scala/org/http4s/blaze/channel/ChannelSpec.scala
When calling ServerChannel.join(), its not clear that tasks may not be
finished executing before the call returns because it's up to the caller
of `close()` to execute all the tasks.
We fix this by making `join()` wait until all tasks have been executed
before returning. To improve the user experience, we also allow passing
an `ExecutionContext` on which to run the shutdown hooks.
> Fix a race condition in ServerChannel

- build.sbt
MiMa says it's binary compatible. This will eliminate an irritating eviction warning on http4s >= 0.16 if we release this as 0.12.7, and bump blaze in http4s.
/cc @ZizhengTai @cquiroz
> Bump to http4s-websocket-0.2.0

- examples/src/main/scala/org/http4s/blaze/examples/ClientExample.scala
- examples/src/main/scala/org/http4s/blaze/examples/ExampleKeystore.scala
- http/src/main/scala/org/http4s/blaze/http/ClientSessionManagerImpl.scala
- http/src/main/scala/org/http4s/blaze/http/HttpClient.scala
- http/src/main/scala/org/http4s/blaze/http/InternalWriter.scala
- http/src/test/scala/org/http4s/blaze/http/ClientSessionManagerImplSpec.scala
A rough example of a pooling session manager. I don't think this should be considered 'production ready' since it doesn't put limits on the number of cached sessions and doesn't do a great job cleaning up bad sessions, but it should be a reasonable starting point and provides a mechanism for demonstrating the HTTP/2 client.
> Add pooled ClientSessionManagerImpl

- http/src/main/scala/org/http4s/blaze/http/http2/FlowStrategy.scala
- http/src/main/scala/org/http4s/blaze/http/http2/SessionFlowControl.scala
- http/src/main/scala/org/http4s/blaze/http/http2/SessionFlowControlImpl.scala
- http/src/main/scala/org/http4s/blaze/http/http2/StreamFlowWindow.scala
- http/src/test/scala/org/http4s/blaze/http/http2/Mocks.scala
- http/src/test/scala/org/http4s/blaze/http/http2/SessionFlowControlSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/StreamFlowWindowSpec.scala
Add configurable flow control for HTTP/2. The FlowStrategy
is responsible for determining when to ACK inbound data.
> Add HTTP/2 flow control tools

- http/src/main/scala/org/http4s/blaze/http/http2/ByteBufferInputStream.scala
- http/src/main/scala/org/http4s/blaze/http/http2/HeaderDecoder.scala
- http/src/main/scala/org/http4s/blaze/http/http2/HeaderEncoder.scala
- http/src/test/scala/org/http4s/blaze/http/http2/ByteBufferInputStreamSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/HeaderCodecHelpers.scala
- http/src/test/scala/org/http4s/blaze/http/http2/HeaderDecoderSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/HeaderEncoderSpec.scala
In HTTP/2 headers are transmitted using the HPACK compression scheme. We use the twitter HPACK implementation under the hood and wrap them in our own classes to provide a convenient interface and allow us to move to a new HPACK implementation in the future.
> Add Header encoder and decoders

- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1SocketServerGroup.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoopPool.scala
- core/src/main/scala/org/http4s/blaze/channel/nio2/NIO2SocketServerGroup.scala
- core/src/main/scala/org/http4s/blaze/util/TickWheelExecutor.scala
Puts a `blaze-*` prefix on all threads created by blaze for easy identification during profiling.
> Call the threads blaze-*

- core/src/main/scala/org/http4s/blaze/channel/nio2/ByteBufferHead.scala
- core/src/test/scala/org/http4s/blaze/channel/ChannelSpec.scala
The nio2.ByteBufferHead will attempt to write an empty
Seq of buffers which can cause problems on some platforms.
Instead we should short circuit and return successful
immediately.
> Don't write an empty Seq of buffers to the socket

- core/src/test/scala/org/http4s/blaze/pipeline/stages/SSLStageSpec.scala
- core/src/test/scala/org/http4s/blaze/pipeline/stages/TimeoutHelpers.scala
- examples/src/main/scala/org/http4s/blaze/examples/ExampleService.scala
- http/src/test/scala/org/http4s/blaze/http/parser/Benchmarks.scala
- http/src/test/scala/org/http4s/blaze/http/parser/ParserBaseSpec.scala
- http/src/test/scala/org/http4s/blaze/http/parser/ServerParserSpec.scala
Not specifying it means you get a platform specific `Charset`.
> Specify Charset in `String.getBytes` calls

- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1SocketServerGroup.scala
- core/src/main/scala/org/http4s/blaze/channel/nio2/NIO2SocketServerGroup.scala
- core/src/test/scala/org/http4s/blaze/channel/ChannelSpec.scala
Closes #111 
If we don't catch exceptions in AsynchronousSocketChannel
we could lose them since the loop is happening asynchronously.
Reported in #97
> catch exceptions in NIO2SocketServerGroup

- .travis.yml
This should fix the current primary issue with publish stage for master on 2.12.3 and 2.11.11
> Fix Typelevel Scala in Compile Stage

- build.sbt
- project/plugins.sbt
This will let us print the blaze version like we do the Tomcat and Jetty versions in http4s/http4s#1536.
> Add build info

- core/src/main/scala/org/http4s/blaze/pipeline/stages/BasicTail.scala
- http/src/main/scala/org/http4s/blaze/http/HttpClientSession.scala
- http/src/main/scala/org/http4s/blaze/http/http2/Http2Connection.scala
- http/src/main/scala/org/http4s/blaze/http/http2/SessionFlowControlImpl.scala
- http/src/main/scala/org/http4s/blaze/http/http2/StreamFlowWindow.scala
- http/src/main/scala/org/http4s/blaze/http/http2/StreamManagerImpl.scala
- http/src/test/scala/org/http4s/blaze/http/ClientSessionManagerImplSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/Http2FrameEncoderSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/StreamManagerImplSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/mocks/MockStreamFlowWindow.scala
We can get by just fine with Http2ClientSession if we add a `ping()`
method.
> Remote Http2ClientConnection and cleanup some interfaces

- core/src/main/scala/org/http4s/blaze/util/TickWheelExecutor.scala
- http/src/main/scala/org/http4s/blaze/http/http2/Connection.scala
- http/src/main/scala/org/http4s/blaze/http/http2/Result.scala
- http/src/main/scala/org/http4s/blaze/http/http2/SessionCore.scala
- http/src/main/scala/org/http4s/blaze/http/http2/SessionFrameListener.scala
- http/src/main/scala/org/http4s/blaze/http/http2/StreamManagerImpl.scala
- http/src/main/scala/org/http4s/blaze/http/http2/StreamStateImpl.scala
- http/src/test/scala/org/http4s/blaze/http/http2/HeaderAggregatingFrameListenerSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/Http2ExceptionSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/OutboundStreamStateImplSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/SessionFrameListenerSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/StreamManagerImplSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/mocks/MockTools.scala
Some general cleanup work including but not limited to:
* Removing the unused `Halt` object
* Defining `isClient` for the SessionCore in terms of having a builder
for inbound stream.
> Cleanup of unused and/or redundant abstractions

- http/src/main/scala/org/http4s/blaze/http/http2/FrameDecoder.scala
- http/src/main/scala/org/http4s/blaze/http/http2/FrameListener.scala
- http/src/main/scala/org/http4s/blaze/http/http2/Http2Settings.scala
- http/src/main/scala/org/http4s/blaze/http/http2/SessionFrameListener.scala
- http/src/main/scala/org/http4s/blaze/http/http2/SettingsDecoder.scala
- http/src/test/scala/org/http4s/blaze/http/http2/FrameDecoderSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/FrameSerializerSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/ProtocolFrame.scala
- http/src/test/scala/org/http4s/blaze/http/http2/ProtocolFrameDecoder.scala
- http/src/test/scala/org/http4s/blaze/http/http2/SessionFrameListenerSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/mocks/MockFrameListener.scala
- http/src/test/scala/org/http4s/blaze/http/http2/mocks/MockHeaderAggregatingFrameListener.scala
Since an ack and settings are mutually exclusive, we can model it
better as Settings(Option[Seq[Setting]]) where None represents an ack
and Some represents a settings frame.
> Refactor Settings related parts of codecs and listeners

- http/src/main/scala/org/http4s/blaze/http/HttpRequest.scala
- http/src/main/scala/org/http4s/blaze/http/http2/client/ClientSessionImpl.scala
- http/src/main/scala/org/http4s/blaze/http/http2/client/ClientStage.scala
- http/src/test/scala/org/http4s/blaze/http/http2/ClientPriorKnowledgeHandshakerSpecSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/ConnectionImplSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/ServerPriorKnowledgeHandshakerSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/client/ClientStageSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/mocks/MockByteBufferHeadStage.scala
- http/src/test/scala/org/http4s/blaze/http/http2/mocks/MockHeadStage.scala
The ClientStage is responsible for handling the dispatch of a HTTP
request which means turning a request and response into and from a
stream of HTTP/2 messages.
The ClientSessionImpl is just a thin wrapper around the HttpConnection.
> Add ClientStage and ClientSessionImpl

- examples/src/main/scala/org/http4s/blaze/examples/http2/H2ClientExample.scala
- http/src/main/scala/org/http4s/blaze/http/BodyReader.scala
- http/src/main/scala/org/http4s/blaze/http/ClientSessionManagerImpl.scala
- http/src/main/scala/org/http4s/blaze/http/http2/client/ALPNClientSelector.scala
- http/src/main/scala/org/http4s/blaze/http/http2/client/ClientSelector.scala
- http/src/main/scala/org/http4s/blaze/http/http2/client/Http2Client.scala
- http/src/main/scala/org/http4s/blaze/http/http2/client/Http2ClientSessionManagerImpl.scala
- http/src/test/scala/org/http4s/blaze/http/ClientSessionManagerImplSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/client/Http2ClientSessionManagerImplSpec.scala
Finally, we have a HTTP/2 client. It still needs a battery of
end-to-end tests which are run against a local server.
> Add Http2Client and the session manager and selectors necessary

- http/src/main/scala/org/http4s/blaze/http/BodyWriter.scala
- http/src/main/scala/org/http4s/blaze/http/http2/client/ClientStage.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/RequestParser.scala
- http/src/main/scala/org/http4s/blaze/http/util/UrlTools.scala
- http/src/test/scala/org/http4s/blaze/http/http2/server/RequestParserSpec.scala
The RequestParser turns a sequence of pseudo-headers and a body into a
legit HttpRequest while rejecting malformed request preludes according
to the spec.
Also some smaller cleanups included.
> Add the server side RequestParser

- http/src/main/scala/org/http4s/blaze/http/http2/server/AbstractBodyWriter.scala
- http/src/test/scala/org/http4s/blaze/http/http2/server/AbstractBodyWriterSpec.scala
It serves as the `BodyWriter` implementation for HTTP/2 server responses.
> Add the HTTP/2 AbstractBodyWriter

- http/src/main/scala/org/http4s/blaze/http/InternalWriter.scala
- http/src/main/scala/org/http4s/blaze/http/http1/server/Http1ServerCodec.scala
- http/src/main/scala/org/http4s/blaze/http/http2/StageTools.scala
- http/src/main/scala/org/http4s/blaze/http/http2/client/ClientStage.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/AbstractBodyWriter.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/ServerStage.scala
- http/src/test/scala/org/http4s/blaze/http/http2/mocks/MockHeadStage.scala
- http/src/test/scala/org/http4s/blaze/http/http2/server/AbstractBodyWriterSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/server/ServerStageSpec.scala
It drives the dispatch of individual stream requests and is a
one-time use abstraction: one per stream.
> Add the HTTP/2 ServerStage

- examples/src/main/scala/org/http4s/blaze/examples/http2/H2ClientExample.scala
- examples/src/main/scala/org/http4s/blaze/examples/http2/Http2ServerExample.scala
- http/src/main/scala/org/http4s/blaze/http/RouteAction.scala
- http/src/main/scala/org/http4s/blaze/http/package.scala
Clean up duplication in the HTTP/2 client examples and add notes about the need for the Jetty ALPN library. Also added some docs to some of the HTTP/2 primitives.
> Cleanup the Http2ClientExample and add some docs

- build.sbt
The first milestone release of the 0.14.0 series, now with a new HTTP/2 server **_and_** client implementation!
> Bump version to 0.14.0-M1 for release

- .travis.yml
In it's current state it just makes a mess of the staging repo, so we
should remove it for now and can reexamine it again later if needed.
> Travis shouldn't try publishing

- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1HeadStage.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoop.scala
- core/src/main/scala/org/http4s/blaze/util/MPSCQueue.scala
- core/src/main/scala/org/http4s/blaze/util/TaskQueue.scala
- core/src/test/scala/org/http4s/blaze/util/TaskQueueSpec.scala
Fixes #164 
Cleanup the `SelectorLoop`. While doing so a task leak was discovered where a `Runnable` could be added to the `SelectorLoop`s queue of tasks to execute, but would never be executed if the selector got closed at a slightly unlucky time.
> SelectorLoop cleanup

- http/src/main/scala/org/http4s/blaze/http/http2/Connection.scala
- http/src/main/scala/org/http4s/blaze/http/http2/ConnectionImpl.scala
- http/src/main/scala/org/http4s/blaze/http/http2/OutboundStreamStateImpl.scala
- http/src/main/scala/org/http4s/blaze/http/http2/StreamFrame.scala
- http/src/main/scala/org/http4s/blaze/http/http2/StreamManagerImpl.scala
- http/src/main/scala/org/http4s/blaze/http/http2/StreamState.scala
- http/src/main/scala/org/http4s/blaze/http/http2/StreamStateImpl.scala
- http/src/main/scala/org/http4s/blaze/http/http2/client/ClientStage.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/AbstractBodyReader.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/AbstractBodyWriter.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/ServerPriorKnowledgeHandshaker.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/ServerSelector.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/ServerStage.scala
- http/src/test/scala/org/http4s/blaze/http/endtoend/scaffolds/Http2ServerScaffold.scala
- http/src/test/scala/org/http4s/blaze/http/http2/ConnectionImplSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/SessionFrameListenerSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/StreamManagerImplSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/client/ClientStageSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/server/AbstractBodyReaderSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/server/AbstractBodyWriterSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/server/ServerStageSpec.scala
This naming is more consistent with what it represents and the
subclasses DataFrame and HeadersFrame.
> Rename StreamMessage to StreamFrame

- examples/src/main/scala/org/http4s/blaze/examples/ExampleService.scala
- http/src/main/scala/org/http4s/blaze/http/HeaderNames.scala
- http/src/main/scala/org/http4s/blaze/http/RouteAction.scala
- http/src/main/scala/org/http4s/blaze/http/http1/server/Http1ServerStage.scala
- http/src/main/scala/org/http4s/blaze/http/http2/DefaultFlowStrategy.scala
- http/src/main/scala/org/http4s/blaze/http/http2/PriorKnowledgeHandshaker.scala
- http/src/main/scala/org/http4s/blaze/http/http2/PseudoHeaders.scala
- http/src/main/scala/org/http4s/blaze/http/http2/StageTools.scala
- http/src/main/scala/org/http4s/blaze/http/http2/client/ClientStage.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/ALPNServerSelector.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/RequestParser.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/ServerPriorKnowledgeHandshaker.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/ServerStage.scala
- http/src/main/scala/org/http4s/blaze/http/util/HeaderTools.scala
- http/src/main/scala/org/http4s/blaze/http/util/ServiceTimeoutFilter.scala
- http/src/test/scala/org/http4s/blaze/http/http2/client/ClientStageSpec.scala
We made a lot of the API private, but some of it should be made public
again for consumption by http4s proper.
> Start opening up the HTTP/2 types for http4s proper consumption

- build.sbt
A milestone which should allow http4s proper to use the 0.14.0.x line.
> Release v0.14.0-M2

- core/src/main/scala/org/http4s/blaze/channel/nio1/FixedSelectorPool.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1SocketServerGroup.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoopPool.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/ServerChannelImpl.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/SocketChannelHead.scala
It was a monolithic body of code, mostly condensed into one method. It
was broken down into methods and a number of classes moved to their own
files.
> Cleanup NIO1SocketServerGroup

- core/src/main/scala/org/http4s/blaze/channel/ServerChannelGroup.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/FixedSelectorPool.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1HeadStage.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1SocketConnection.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1SocketServerGroup.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoop.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoopPool.scala
- core/src/main/scala/org/http4s/blaze/channel/package.scala
- core/src/main/scala/org/http4s/blaze/util/BasicThreadFactory.scala
- core/src/test/scala/org/http4s/blaze/channel/ChannelSpec.scala
Closes #183.
Using a ThreadFactory to generate the threads for the SelectorLoops
and NIO1SocketServerGroup gives users an easy way to control how
threads are created and their properties.
> NIO1 event loops use a ThreadFactory to spawn threads

- core/src/main/scala/org/http4s/blaze/channel/ServerChannelGroup.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1SocketServerGroup.scala
- core/src/main/scala/org/http4s/blaze/channel/nio2/NIO2SocketServerGroup.scala
- core/src/main/scala/org/http4s/blaze/channel/package.scala
- core/src/main/scala/org/http4s/blaze/pipeline/PipelineBuilder.scala
- core/src/main/scala/org/http4s/blaze/pipeline/stages/monitors/ConnectionMonitor.scala
- core/src/test/scala/org/http4s/blaze/channel/ChannelSpec.scala
- examples/src/main/scala/org/http4s/blaze/examples/EchoServer.scala
- examples/src/main/scala/org/http4s/blaze/examples/Http1ServerExample.scala
- examples/src/main/scala/org/http4s/blaze/examples/http2/Http2ServerExample.scala
- http/src/main/scala/org/http4s/blaze/http/http1/server/Http1Server.scala
- http/src/test/scala/org/http4s/blaze/http/endtoend/scaffolds/ServerScaffold.scala
Closes #184.
The `acceptConnection` method is in a silly place in that the
`ServerSocketGroup` represents a collection of resources that are
capible of listening for socket connections. It is the wrong place to be
defining the logic for accepting or rejecting connections. This is
better done via changing the definition of `BufferPipelineBuilder` from
`SocketConnection => LeafBuilder[ByteBuffer]`
to
`SocketConnection => Option[LeafBuilder[ByteBuffer]]`
It also makes sense to rename `BufferPipelineBuilder` to
`SocketPipelineBuilder` since it must be dealing in `SocketConnection`s.
> ServerChannelGroup.acceptConnection is moved to `BufferedPipelinebuilder`

- build.sbt
This is mostly to get rid of the warning reported by @coltfred on Gitter and fixed by @felixmulder in #193. Picks up some other stuff while we're here.
> Release v0.12.12 with dependency bumps

- core/src/main/scala/org/http4s/blaze/channel/ChannelHead.scala
- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1HeadStage.scala
- core/src/main/scala/org/http4s/blaze/channel/nio2/ByteBufferHead.scala
- core/src/main/scala/org/http4s/blaze/pipeline/Command.scala
- core/src/main/scala/org/http4s/blaze/pipeline/Stages.scala
- core/src/main/scala/org/http4s/blaze/pipeline/stages/TimeoutStageBase.scala
- core/src/test/scala/org/http4s/blaze/pipeline/stages/QuietTimeoutStageSpec.scala
- core/src/test/scala/org/http4s/blaze/pipeline/stages/TimeoutHelpers.scala
- http/src/main/scala/org/http4s/blaze/http/http1/client/Http1ClientStage.scala
- http/src/main/scala/org/http4s/blaze/http/http1/server/Http1ServerStage.scala
Right now, when a channel fails to read or write it fails the channel,
closing everything etc. This makes it impossible to handle half-closed
scenarios. Instead of the Head being in charge of releasing resources,
we move that responsibility to the tails. This allows them to interact
with a half closed socket.
Note: this doesn't yet allow half-closing a socket, though it is a
necessary step.
> Tails are in charge of closing resources

- core/src/main/scala/org/http4s/blaze/channel/nio2/ByteBufferHead.scala
- core/src/main/scala/org/http4s/blaze/util/Property.scala
- http/src/main/scala/org/http4s/blaze/http/HttpRequest.scala
- http/src/main/scala/org/http4s/blaze/http/HttpResponsePrelude.scala
- http/src/main/scala/org/http4s/blaze/http/http1/client/Http1ClientStage.scala
- http/src/main/scala/org/http4s/blaze/http/logsensitiveinfo.scala
The HttpRequest and HttpResponsePrelude are case classes which will
expose the headers in the default `toString` method implementation.
Instead, we now implement a safe `toString` method but also provide an
`unsafeToString` method for cases where you really want them.
> Make HTTP message toString safe by default

- core/src/main/scala/org/http4s/blaze/pipeline/Command.scala
- core/src/main/scala/org/http4s/blaze/pipeline/Stages.scala
- http/src/main/scala/org/http4s/blaze/http/http2/StreamStateImpl.scala
- http/src/main/scala/org/http4s/blaze/http/http2/client/ClientPriorKnowledgeHandshaker.scala
Related to #198
Only the `ClientChannelFactory` is making client channels, and they
start life connected, so essentially the `Connect` command is dead code.
Seems like a good time to remove it.
> Remove the `Connect` command

- build.sbt
Intent is to release this and http4s and get the new close handler without warnings about binary clashes.
> Upgrade to http4s-websocket-0.2.1

- http/src/main/scala/org/http4s/blaze/http/BodyWriter.scala
- http/src/main/scala/org/http4s/blaze/http/RouteAction.scala
- http/src/main/scala/org/http4s/blaze/http/http1/server/Http1ServerCodec.scala
- http/src/main/scala/org/http4s/blaze/http/http2/InboundStreamStateImpl.scala
- http/src/main/scala/org/http4s/blaze/http/http2/OutboundStreamStateImpl.scala
- http/src/main/scala/org/http4s/blaze/http/http2/StreamState.scala
- http/src/main/scala/org/http4s/blaze/http/http2/StreamStateImpl.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/AbstractBodyWriter.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/ServerStage.scala
- http/src/test/scala/org/http4s/blaze/http/http2/StreamStateImplSpec.scala
- http/src/test/scala/org/http4s/blaze/http/http2/server/AbstractBodyWriterSpec.scala
Right now, there is no way for a user of a BodyWriter to signal to the
consuming side that it is being closed due to some problem, thus the
other end may think that the stream closed successfully, while in
reality it may be incomplete.
To fix this, we add a `cause: Option[Throwable]` to the `close` method
to allow the data producer to signal that it is closing due to a
problem.
> Add ability to close a BodyWriter with an exception

- core/src/test/scala/org/http4s/blaze/pipeline/stages/SSLStageSpec.scala
- http/src/main/scala/org/http4s/blaze/http/http2/FrameDecoder.scala
- http/src/test/scala/org/http4s/blaze/http/parser/ServerParserSpec.scala
this turned up in the Scala 2.12 community build at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk9-integrate-community-build/351/consoleFull
> tweak sources to compile on JDK 9

- http/src/test/scala/org/http4s/blaze/http/endtoend/InfiniteSpec.scala
While tracking a bug with infinite server side response streams  and disconnected clients I came up with this new test. At the end the test demonstrated that there was no issue in Blaze, but I think it can still be useful to have it to avoid any future regression.
> Add a new end-to-end test

- build.sbt
- core/src/main/scala/org/http4s/blaze/pipeline/Stages.scala
- project/BlazePlugin.scala
Proposing this intermediate release to unblock http4s milestone.
Fixes #218 by quieting `Disconnected` events.  These are not handled by `Http1ServerStage`, `QuietTimeoutStage`, `SSLStage`, which causes at least 2 warnings on every request, 3 if SSL.  HTTP/2 and websockets are probably also affected.  Maybe we ignore these at our own peril.
Catching up to the demise of `OutboundCommand` is left for https://github.com/http4s/http4s/issues/2058, but we need a milestone now.
Backported #216 in order to avoid dependency warnings on log4s.
This should be merged back to master after release.
> Release v0.14.0-M4

- core/src/main/scala/org/http4s/blaze/pipeline/Stages.scala
- project/build.properties
- project/plugins.sbt
These changes were made to get http4s out the door.
Getting http4s back on the mainline is the subject of http4s/http4s#2058 and not covered here, though this will help.
>  Merge v0.14.0-M4 changes into master

- .travis.yml
- build.sbt
- project/BlazePlugin.scala
- project/plugins.sbt
- websocket was ripped out
- scalaXml disappeared a while back
- alpn-boot is a runtime dependency
> Clean up unused dependencies

- core/src/main/scala/org/http4s/blaze/pipeline/stages/QuietTimeoutStage.scala
- core/src/main/scala/org/http4s/blaze/pipeline/stages/TimeoutStage.scala
- core/src/main/scala/org/http4s/blaze/pipeline/stages/TimeoutStageBase.scala
- core/src/main/scala/org/http4s/blaze/util/Cancelable.scala
- core/src/main/scala/org/http4s/blaze/util/TickWheelExecutor.scala
- core/src/test/scala/org/http4s/blaze/pipeline/stages/QuietTimeoutStageSpec.scala
- core/src/test/scala/org/http4s/blaze/pipeline/stages/TimeoutHelpers.scala
Instead of closing the pipeline with an exception on timeout, send an inbound command.  This will let an HTTP-aware stage return a 503 if the response is not yet committed.
```scala
[info] [blaze-selector-0-1] ERROR o.h.b.c.n.NIO1HeadStage - Abnormal NIO1HeadStage termination 
[info] java.util.concurrent.TimeoutException: Timeout of 30 seconds triggered. Killing pipeline.
[info] at org.http4s.blaze.pipeline.stages.TimeoutStageBase$$anon$1.run(TimeoutStageBase.scala:29)
[info] at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66) 
[info] at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:261)
[info] at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:193
[info] at …
```
> Refactor TimeoutStage

- core/src/main/scala/org/http4s/blaze/pipeline/Stages.scala
It's idempotent, and so is stage shutdown. No reason to scare people in the logs.
> Don't warn on the removal of a disconnected MidStage

- core/src/main/scala/org/http4s/blaze/channel/nio1/NIO1SocketServerGroup.scala
@SebastianVoss [reports](https://gitter.im/http4s/http4s?at=5bd8a75d600c5f6423313cbd) this error:
```
project examples-blaze
runMain com.example.http4s.blaze.BlazeSslExample
```
```
19:41:53.274 [blaze-selector-0-1] INFO  o.h.b.c.nio1.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:58481
19:42:02.796 [blaze-selector-0-0] ERROR o.h.b.c.nio1.NIO1SocketServerGroup - Listening socket(/127.0.0.1:8443) closed forcibly.
java.net.SocketException: Invalid argument
at sun.nio.ch.Net.setIntOption0(Native Method)
at sun.nio.ch.Net.setSocketOption(Net.java:334)
at sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:190)
at sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:43)
at org.http4s.blaze.channel.ChannelOptions.$anonfun$applyToChannel$1(ChannelOptions.scala:12) …
```
> Handle exceptions handling client channels

- core/src/main/scala/org/http4s/blaze/pipeline/stages/SSLStage.scala
Should fix https://github.com/http4s/blaze/issues/258
> Handshake status can change to FINISHED, even if wrap produced no data.

- version.sbt
Most critically, adds 2.13.0-M5 support.
> Release v0.14.0-RC1

- core/src/main/scala/org/http4s/blaze/channel/ChannelHead.scala
By mistake I reported the issue in http4s, more details available there: https://github.com/http4s/http4s/issues/2496
Fixes: https://github.com/http4s/http4s/issues/2496
> Add "The scpecified network name is no longer available\r\n" to the brokenPipeMessages.

- core/src/main/scala/org/http4s/blaze/pipeline/stages/SSLStage.scala
Cleanup SSL Engine during connection close. 
With JDK SSLContext, this is not required. With native ssl context(Ex: conscrypt), calling close() methods frees up native memory associated with each connection. Otherwise, system will leak memory for every connection.
> SSL Engine cleanup

- core/src/main/scala/org/http4s/blaze/channel/nio2/ClientChannelFactory.scala
- core/src/main/scala/org/http4s/blaze/util/TickWheelExecutor.scala
- core/src/test/scala/org/http4s/blaze/channel/nio2/ClientChannelFactorySpec.scala
- core/src/test/scala/org/http4s/blaze/test/FastTickWheelExecutor.scala
This PR is motivated by repeating issues around connecting timeouts in http4s:
- https://github.com/http4s/http4s/issues/2386
- https://github.com/http4s/http4s/issues/2338
- https://github.com/http4s/http4s/issues/2690
The current state of connecting timeouts in http4s is that a timeout should happen eventually, but **when** it will happen is up to the OS. For example I've measured 15 seconds on Windows 7 and 135 seconds on Ubuntu 16.04, and @kamilkloch  (https://github.com/http4s/http4s/issues/2690) reports that in his environment the timeout doesn't happen at all. 
For comparison other http client libraries let users configure the timeout: 
- [`akka-http`](https://github.com/akka/akka-http/blob/eb7311130021c6fa72dff05090c20568ee1319dd/akka-http-core/src/main/resources/reference.conf#L25 …
> Implement connecting timeout in ClientChannelFactory.

- http/src/main/scala/org/http4s/blaze/http/http1/client/Http1BodyEncoder.scala
- http/src/test/scala/org/http4s/blaze/http/http1/client/Http1ClientStageSpec.scala
As per the [RFC](https://tools.ietf.org/html/rfc7230#section-4.1). Found it when I was trying to connect blaze `HttpClient` to a http4s server.
Please release a new version with this fix.
> Add trailing CRLF to chunks in ChunkedTransferEncoder

- core/src/main/scala/org/http4s/blaze/pipeline/stages/SSLStage.scala
Hi! 
Recently we've faced an issue on our production env with http4s client - https://github.com/http4s/http4s/issues/2744.
I finally got some time to investigate it a bit more and found that the problem was lying in `org.http4s.blaze.pipeline.stages.SSLStage#sslHandshake#sslHandshakeLoop` in this arm:
```
case HandshakeStatus.NEED_WRAP =>
val o = getScratchBuffer(maxBuffer)
val r = engine.wrap(emptyBuffer, o)
logger.trace(s"SSL Handshake Status after wrap: $r")
o.flip()
if (r.bytesProduced < 1 && r.getHandshakeStatus != HandshakeStatus.FINISHED)
handshakeFailure(new SSLException(s"SSL Handshake WRAP produced 0 bytes: $r"))
channelWrite(copyBuffer(o)).onComplete {
case Success(_) => sslHandshake(data, r.getHandshakeStatus)
case Failure(t) => handshakeFailure(t)
}(serialExec)
```
There was …
> Fixes http4s#2744 and http4s#2192

- http/src/main/java/org/http4s/blaze/http/parser/BaseExceptions.java
- http/src/main/java/org/http4s/blaze/http/parser/BodyAndHeaderParser.java
- http/src/main/java/org/http4s/blaze/http/parser/Http1ClientParser.java
- http/src/main/java/org/http4s/blaze/http/parser/Http1ServerParser.java
- http/src/main/java/org/http4s/blaze/http/parser/HttpTokens.java
- http/src/main/java/org/http4s/blaze/http/parser/ParserBase.java
Extends #409 by formatting the result.
As an old Java developer, I'm not thrilled about the two-space indent, but it's closer to Scala and there was a convenient tool on hand.
> Reformat Java

- core/src/main/scala/org/http4s/blaze/channel/nio2/ByteBufferHead.scala
Addresses [graceless handling of OOME](https://gitter.im/http4s/http4s?at=5f980c77bbffc02b58421870).
```
Exception in thread "Thread-42" scala.MatchError: java.lang.OutOfMemoryError: Direct buffer memory (of class java.lang.OutOfMemoryError)
at org.http4s.blaze.channel.nio2.ByteBufferHead.checkError(ByteBufferHead.scala:107)
at org.http4s.blaze.channel.nio2.ByteBufferHead$$anon$1.failed(ByteBufferHead.scala:51)
at org.http4s.blaze.channel.nio2.ByteBufferHead$$anon$1.failed(ByteBufferHead.scala:49)
at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
at sun.nio.ch.Invoker$2.run(Invoker.java:219)
at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at …
```
> Don't assume checkError is called on NonFatal

- core/src/main/scala/org/http4s/blaze/pipeline/Stages.scala
This is my first attempt at a solution for https://github.com/http4s/http4s/issues/1256 . It turns out that the bug is actually benign and has only been observed to occur during connection shutdowns, so it should never actually cause any issues. Either way, people get understandably worried when they see exceptions, so we should try to clean that up.
The bug is really just a consequence of the fact that the Blaze pipeline is mutable and there is no synchronization over modifications to the pipeline. So for example, in the original issue, what's happening is that the `IdleTimeoutStage` is trying to send a message inbound, but its next stage is `null`, so it can't really continue. As far as I know, the only way this can happen is when a stage removes itself from the pipeline, but an …
> Don't fail on inbound message

- project/Dependencies.scala
There's no reason to be on a milestone until we have Dotty support.
> Downgrade to log4s-1.9.0

- core/src/test/scala/org/http4s/blaze/channel/ChannelSpec.scala
This should not make a difference, but similar did at a similar time in the main repo.
> Bind ChannelSpec channels to localhost

- .gitignore
- README.md
- build.sbt
- examples/src/main/scala/org/http4s/blaze/examples/http2/H2ClientExample.scala
- http/src/main/scala/org/http4s/blaze/http/http2/client/ALPNClientSelector.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/ALPNServerSelector.scala
- http/src/main/scala/org/http4s/blaze/http/http2/server/ServerSelector.scala
- project/Dependencies.scala
Before (curl output):
```
vasil@vasil-mac ~ % curl -v -k https://127.0.0.1:8443/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* …
```
> Use JDK platform APIs for ALPN negotiation

- .github/workflows/ci.yml
- build.sbt
- project/Dependencies.scala
- project/plugins.sbt
Same issue with sbt-dotty as in vault and case-insensitive.
Additionally, a 3.0 compatible version of log4s is still missing: https://github.com/Log4s/log4s/pull/76
> Upgrade Scala to 3.0.0

- core/src/main/scala/org/http4s/blaze/util/TickWheelExecutor.scala
The motivation for this is to make it possible to not submit a new task when the TickWheelExecutor is being shutdown.
This mostly happens at the end, so we just want to make sure we dont submit or fail with an exception.
> Add package private isAlive and specific Exception type

- core/src/main/scala/org/http4s/blaze/util/TickWheelExecutor.scala
Speculative fix for #552.  At least brings our implementation closer to those referenced.
> Use monotonic time in TickWheelExecutor

- nix/nixpkgs-version.json
I couldn't build on a Mac with the old version.  It was missing things on SSLEngine.
> Freshen the JDK in the Nix shell

- .github/workflows/ci.yml
- build.sbt
This tries to fix #555. It seems that the `githubWorkflowPublishTargetBranches` should be set only once. However, I'm not sure that it's the root of the problem.
> Set `githubWorkflowPublishTargetBranches` only once in the build.sbt

- .github/workflows/ci.yml
- build.sbt
Before:
```
% sbt projects
...
[info]   * blaze
[info]     blaze-core
[info]     blaze-examples
[info]     blaze-http
[info]     blaze-testkit
[info]     blazeClient
[info]     blazeCore
[info]     blazeServer
```
After:
```
% sbt projects
...
[info]   * blaze
[info]     blaze-core
[info]     blaze-examples
[info]     blaze-http
[info]     blaze-testkit
[info]     http4s-blaze-client
[info]     http4s-blaze-core
[info]     http4s-blaze-server
```
> Make sbt recognise the names of the http4s-* projects

- build.sbt
Use .scalafmt.conf for the root project, because that's what scala steward assumes
> Fix ScalaStewart reformatting build.sbt

- .mergify.yml
An attempt to set up attaching those nice labels like in `http4s`.
> Set up `mergify.yml`

- build.sbt
Since we migrated to versioning like in `http4s`, and the `main` now relates to the `1.0.0-X` series, we can do this refactoring.
> Clean up Mima filters in `build.sbt`

- .github/workflows/ci.yml
- .scala-steward.conf
- build.sbt
On updating Scala 3 from 3.0.x to 3.1.x we forgot to update the Scala Steward config. So we are stuck on Scala 3.1.2 for a while. Let's fix this.
> Fix Scala 3 updating

- core/src/test/scala/org/http4s/blaze/pipeline/stages/SSLStageSuite.scala
- testkit/src/main/scala/org/http4s/blaze/testkit/BlazeTestSuite.scala
Alternative to #771.  Better discussion there, but this reflects that we don't yet understand it, but also lets us move forward.
> Mark "split large buffers" test flaky

- blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
- blaze-client/src/main/scala/org/http4s/blaze/client/PoolManager.scala
- blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala
- blaze-core/src/main/scala/org/http4s/blazecore/util/package.scala
- blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala
- blaze-server/src/main/scala/org/http4s/blaze/server/Http2NodeStage.scala
- blaze-server/src/test/scala/org/http4s/blaze/server/Http1ServerStageSpec.scala
- build.sbt
- examples/src/main/scala/com/example/http4s/blaze/demo/server/Module.scala
- examples/src/main/scala/com/example/http4s/blaze/demo/server/Server.scala
- examples/src/main/scala/com/example/http4s/blaze/demo/server/service/FileService.scala
This is a fairly urgent fix after cats-effect-3.5.0.
* Fixes deprecation warnings from fs2-3.7.0
* Addresses changes to semantics of `F.async_`.  The general strategy is to shutdown the stage.  Many of the changes are whitespace.
> Upgrade to http4s-0.23.19

- .scala-steward.conf
As discussed in #786 and brought back to fore by #800.  Can unpin this if someone wants to dig into why our trailing commas keep disappearing.
> Pin scalafmt to 3.6.x

- blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
- blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala
- blaze-core/src/main/scala/org/http4s/blazecore/util/NullWriter.scala
- blaze-server/src/main/scala/org/http4s/blaze/server/Http1ServerStage.scala
- blaze-server/src/test/scala/org/http4s/blaze/server/ServerTestRoutes.scala
We are aggressively closing connections in the presence of `Connection` headers composed exclusively of options other than `keep-alive` or `close`.  This is contrary to [the RFC](https://datatracker.ietf.org/doc/html/rfc9112#section-9.3)
- `Connection` tokens other than `close` and `keep-alive` are no longer considered in persistence logic.
- blaze-server will no longer add an implicit `Connection: close` header to the response unless required by RFC 9112.
- blaze-client will no longer add a duplicate `Connection: close` header when the request already has one.
Replaces #913, which targeted the incorrect branch.
> Fix Connection persistence according to RFC 9112
